add AUR
oguzhaninan/Stacer pull request #474
Opened 2022-01-28 14:49 UTC by boofiboi

Added setup info for Arch linux as stacer is on the AUR

2022-02-09 17:06 UTC, alimkoca requested changes
...needs some commands :)

2022-02-09 17:07 UTC, alimkoca commented
hmm wait

2022-02-09 19:27 UTC, boofiboi commented
Added some comamnds for popular AUR helpers.

2022-02-12 10:27 UTC, alimkoca commented
Cool

2022-07-25 09:08 UTC, merged